version: '3'

services:
  
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    hostname: azuresqledge
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --blobPort 10000 --queuePort 10001 --loose --skipApiVersionCheck"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"